version: 2
updates:
  # Atualiza dependências npm
  - package-ecosystem: "npm"
    directory: "/"               # Raiz do projeto (onde está o package.json)
    schedule:
      interval: "weekly"         # Pode ser daily, weekly ou monthly
      day: "monday"              # Dia da semana para rodar
      time: "06:00"              # UTC (03:00 no horário de Brasília)
    open-pull-requests-limit: 5  # Quantas PRs simultâneas no máximo
    commit-message:
      prefix: "deps"             # PRs ficarão tipo: deps: bump express from 4.17.2 to 4.18.0
    labels:
      - "dependencies"
    rebase-strategy: "auto"      # Mantém PRs sempre atualizadas
